server:
  # 应用服务 WEB 访问端口
  port: 8081

spring:
  # 应用名称
    application:
      name: stockServer
    cloud:
      nacos:
        config:
          file-extension: yaml
        discovery:
          # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
          server-addr: 127.0.0.1:8848
          # Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
          # Nacos认证信息
          username: nacos
          password: nacos
          # 注册到 nacos 的指定 namespace，默认为 public
          namespace: public
